#!/usr/bin/env python3
"""Convert a PNG image to RGB565 for use on the Pico display.

Usage:
  python tools/convert.py input.png output.raw            # raw binary (MicroPython)
  python tools/convert.py input.png output.h --header     # C header  (Arduino)
  python tools/convert.py input.png output.h --header --name MY_SPRITE

Default output size: 120x120
"""

import sys
import argparse
from pathlib import Path
from PIL import Image


def to_rgb565_bytes(input_path, width=120, height=120):
    img = Image.open(input_path).convert("RGB").resize(
        (width, height), Image.Resampling.NEAREST
    )
    buf = bytearray()
    for r, g, b in img.getdata():
        color = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        buf.append(color >> 8)
        buf.append(color & 0xFF)
    return buf


def write_raw(buf, output_path):
    with open(output_path, "wb") as f:
        f.write(buf)
    print(f"Saved {len(buf)} bytes to {output_path}")


def write_header(buf, output_path, sprite_name):
    name = sprite_name.upper()
    lines = [
        "// Auto-generated by tools/convert.py -- do not edit",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
        f"const uint8_t SPRITE_{name}[] PROGMEM = {{",
    ]
    row = []
    for i, byte in enumerate(buf):
        row.append(f"0x{byte:02X}")
        if len(row) == 16:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Saved C header ({len(buf)} bytes) to {output_path}  [SPRITE_{name}]")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("input",  help="Input PNG file")
    parser.add_argument("output", help="Output file (.raw or .h)")
    parser.add_argument("--header", "-H", action="store_true",
                        help="Output a C header instead of raw binary")
    parser.add_argument("--name", "-n", default=None,
                        help="Sprite name for C header (default: stem of output filename)")
    parser.add_argument("--width",  "-W", type=int, default=120)
    parser.add_argument("--height", type=int, default=120)
    args = parser.parse_args()

    try:
        buf = to_rgb565_bytes(args.input, args.width, args.height)
    except FileNotFoundError:
        print(f"Error: input file not found: {args.input}")
        sys.exit(1)

    if args.header:
        name = args.name or Path(args.output).stem
        write_header(buf, args.output, name)
    else:
        write_raw(buf, args.output)
